name: Chocolatey Package Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md" # Ignore markdown files or other files that wouldn't affect the package

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Pack Chocolatey Package
        run: |
          # Pack the Chocolatey package
          choco pack

          # Find the .nupkg file that was just created
          $package = Get-ChildItem -Path . -Filter *.nupkg
          Write-Host "Package packed: $($package.FullName)"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [pack]
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Chocolatey
        run: |
          choco apikey --api-key ${{secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/

      - name: Push Chocolatey Package
        run: |
          # Find all .nupkg files matching the pattern "Ollama*.nupkg"
          $packages = Get-ChildItem -Path . -Filter 'Ollama*.nupkg' -Name

          # Push the package to Chocolatey
          choco push $package.FullName --source https://push.chocolatey.org/
        env:
          CHOCO_API_KEY: ${{secrets.CHOCO_API_KEY}}
